manifest:
  defaults:
    revision: v0.3
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: joelspadin
      url-base: https://github.com/joelspadin
    - name: schmidma
      url-base: https://github.com/schmidma
  projects:
    - name: zmk
      remote: schmidma
      revision: fa16dd720002bb14976005fe1f353d0b8f5af5aa
      import: app/west.yml
    - name: zmk-locales
      remote: joelspadin
      revision: main
  self:
    path: config
