manifest:
  defaults:
    revision: v0.3
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: joelspadin
      url-base: https://github.com/joelspadin
    - name: schmidma
      url-base: https://github.com/schmidma
  projects:
    - name: zmk
      remote: schmidma
      revision: 17dfb0a51df7c65139d4b5f52535773f2d6f2003
      import: app/west.yml
    - name: zmk-locales
      remote: joelspadin
      revision: main
  self:
    path: config
